### ISSUE TITLE
How to use DaggerMock with MockWebServer

### ISSUE THREAD

**Issue by lenguyenthanh** [fabioCollini/DaggerMock#10]
Firstly, I want to thank you for a great library. Then I have a question with MockWebServer. I'm trying to do some integration tests, so I use MockWebServer to test it. But I cannot setup it with DaggerMock. Here is my code:

````
// Retrofit
  @Provides
  @Singleton
  public Retrofit provideRetrofit(@NonNull OkHttpClient okHttpClient,
      @NonNull Configuration configuration, @NonNull Converter.Factory factory) {
    return new Retrofit.Builder().baseUrl(configuration.getBaseApiUrl())
        .client(okHttpClient)
        .addConverterFactory(factory)
        .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
        .validateEagerly(BuildConfig.DEBUG)
        .build();
  }

//Custom Rule 
public class ServerMockRule extends DaggerMockRule<SnowBallApplication.AppComponent> {

  private MockWebServer mockWebServer;

  public ServerMockRule() {
    super(SnowBallApplication.AppComponent.class,
        new AppModule(IntegrationRobolectricTestRunner.snowballApp()));

    mockWebServer = new MockWebServer();
    try {
      mockWebServer.start();
    } catch (IOException e) {
      e.printStackTrace();
    }

    Configuration configuration = Mockito.mock(Configuration.class);
    Mockito.when(configuration.getBaseApiUrl()).thenReturn(mockWebServer.url("").toString());

    provides(Configuration.class, configuration);
  }

  public MockWebServer getMockWebServer() {
    return mockWebServer;
  }
}

// class tests
@Rule
  public ServerMockRule serverMockRule = (ServerMockRule)new ServerMockRule().set((appComponent) -> restApi = appComponent.videoService());

  VideoService restApi;
  
  @Test
  public void testVideos() throws Exception {
    serverMockRule.getMockWebServer().enqueue(new MockResponse().setBody(response));

    // Get items from the API
    List<VideoEntity> videoEntities = restApi.videos().toBlocking().first();

    assertThat(videoEntities).hasSize(3);
  }
````

In this code, I try to change real Url with MockWebServer url inside the custom rules. But it always calls real url instead of mock url. How can I fix this problem. Thanks

**Comment by fabioCollini** [comment]
Hi,
how do you define the Configuration object? Do you create it in a module or are you defining it using @Inject annotation?
DaggerMock dynamically creates a module subclass, it works only if you define the object you want to replace in a module. Is this your problem?

**Comment by lenguyenthanh** [comment]
Thank you so much, I forgot about it. I create Configuration class in another module not AppModule, that why DaggerMock cannot override Configuration.

I have another question is now we have to declare all methods on module with public keyword? I know that it's caused by DaggerMock will not be the same package as a module, but can we have better option?

**Comment by fabioCollini** [comment]
I don't like the public constraint on methods either. It's not about the same package, it's a strange bug that happens only in instrumentations tests (it works on plain junit tests). I think it's related to dexmaker but I am not sure.
To avoid errors I added the constraint on method visibility, I don't like it but it's just a "stylistic" problem because you never invoke the module methods.

**Comment by lenguyenthanh** [comment]
Sorry @fabioCollini, I forgot to say thanks to you. You helped me a lot. Thank you so much.
