### ISSUE TITLE
DaggerMock with pure JVM Kotlin project

### ISSUE THREAD

**Issue by theapache64** [fabioCollini/DaggerMock#106]
Is this library supposed to work with pure JVM + Kotlin+ JUnit project ?

**Comment by fabioCollini** [comment]
Yes, it should work. It doesn't contain any reference to Android, if you look at the repo the module `daggerMockTests` is a pure JVM module

**Comment by theapache64** [comment]
Awesome :+1: . Just wanted to confirm before starting the project.
