### ISSUE TITLE
Multiple params in SubComponent

### ISSUE THREAD

**Issue by digitalbuddha** [fabioCollini/DaggerMock#11]
This looks like a really useful library. I can't seem to figure out how you're able to set module constructor params on SubComponent modules.

So I have an ActivityModule that has the following constructor
`public MainActivityModule(Activity mainActivity, Long timeout) {
        this.activity = mainActivity;
    }
`
How would DaggerMock know what value to pass into the constructor.  Thank you kindly and thank you for a great library.

**Comment by fabioCollini** [comment]
Have you already solved this issue? Was it a problem related to Dagger version?

**Comment by mateuyabar** [comment]
I think I'm having the same problem. My module requires the context to be build.

My module is something like:
```java
@Module
public class DataModule {
    MyApplication context;

    public DataModule(MyApplication context) {
        this.context = context;
    }

    @Provides
    @Singleton
    public SharedPreferences provideSharedPreferences(Context context){
        return PreferenceManager.getDefaultSharedPreferences(context);
    }
(...)
```
I need the context 

However, in the Rule definition, the AppContext has not been created yet:

```java
@Rule public DaggerMockRule<MyComponent> daggerRule = new DaggerMockRule<>(MyComponent.class, new DataModule())...
```

Is there anyhow to solve this?

**Comment by fabioCollini** [comment]
Are you using Espresso or JVM test?
I have created an example with something similar, you can find the source here: https://github.com/fabioCollini/DaggerMock/tree/master/RealWorldApp
