### ISSUE TITLE
How to create the rule class if create a Module instance need parameters

### ISSUE THREAD

**Issue by AvatarQing** [fabioCollini/DaggerMock#18]
I'm writing a Robolectric test, I see the Rule creation of the demo is :

```
  @Rule public final DaggerMockRule<MyComponent> rule = new DaggerMockRule<>(MyComponent.class, new MyModule())
            .set(new DaggerMockRule.ComponentSetter<MyComponent>() {
                @Override public void setComponent(MyComponent component) {
                    ((App) RuntimeEnvironment.application).setComponent(component);
                }
            });
```
Now if `MyModule`'s constructor need a parameter such as `LoginActivity` or `MyApplication`, how do I create the rule class?

**Comment by fabioCollini** [comment]
If you need the app in a Robolectric test you can use `RuntimeEnvironment.application`, something similar to this example: https://github.com/fabioCollini/DaggerMock/blob/master/app/src/test/java/it/cosenonjaviste/daggermock/demo/robolectric/MainActivityTest.java

Passing an Activity as parameter is not supported and I am not sure if it can be useful. Usually the module with the activity as parameter is created inside the activity and it contains objects that you want to test (and not to replace with mocks).

**Comment by AvatarQing** [comment]
Yes, you are right. I'm looking for a elegant way to mock the module which is created inside the activity, if module's constructor requires a activity instance, it looks hard to mock.
