### ISSUE TITLE
Support mocking @Inject constructor injection?

### ISSUE THREAD

**Issue by ChrisZou** [fabioCollini/DaggerMock#20]
Hi @fabioCollini, I notice that DaggerMock does not support constructor injection. If I want to make a mock of a class that has a @Inject constructor in my test using DaggerMock, I have to add a @Provides method in my Module and remove the @Inject annotation on the constructor. I think it would be quite convenient if DaggerMock support mocking classes that have @Inject constructor. Do you have any plans for that?

**Comment by scompt** [comment]
@fabioCollini Is there a reason for this limitation?

**Comment by fabioCollini** [comment]
Hi, this problem is not related to constructor/field injection. The problem is that an object can be replaced with another only if it's defined in a module. Unfortunately this limitation cannot be removed (but there is the same limitation also if you manually create a module subclass).

**Comment by Mathematicalfunk** [comment]
I would also find this valuable. I haven't tried implementing it yet and am probably missing something glaringly obvious, but changing from just injecting mocks from the component to accessing the MembersInjector<ClassToInject> and using that to inject the mocks will allow for any annotated mock objects to be injected into the testObject.

**Comment by fabioCollini** [comment]
I am trying to avoid using generated Dagger classes, so the MembersInjector classes are not used yet. In this way DaggerMock works (or should work!) using all Dagger versions.
