### ISSUE TITLE
run one class vs run all test classes

### ISSUE THREAD

**Issue by tonilopezmr** [fabioCollini/DaggerMock#21]
When Run only one class the Mock is successfully but when run all test doesn't replace my mock.

[This is the test code](https://github.com/tonilopezmr/Game-of-Thrones/blob/master/app/src/androidTest/java/es/npatarino/android/gotchallenge/common/view/activities/DetailActivityTest.java)

[This is the inject code](https://github.com/tonilopezmr/Game-of-Thrones/blob/master/app/src/main/java/es/npatarino/android/gotchallenge/characters/list/view/fragment/CharacterListFragment.java#L52)

[This is the component](https://github.com/tonilopezmr/Game-of-Thrones/blob/master/app/src/main/java/es/npatarino/android/gotchallenge/characters/di/CharacterComponent.java)

I don't know why because i think is the same execute one test or all test. :(

Do you have any idea?

**Comment by tonilopezmr** [comment]
Okey, now I just added this: 

```gradle
debug {
 applicationIdSuffix ".debug"
}
``` 

And now the mocks doesn't work, why? do you know?

Thanks!

**Comment by tonilopezmr** [comment]
Could be for DaggerMockRule? @fabioCollini

**Comment by fabioCollini** [comment]
Hi Antonio, I am sorry but I can't investigate this problem until September. Are you using espresso or plain junit tests? Is it a multidex app?

**Comment by tonilopezmr** [comment]
Espresso and not multidex.

it's very weird, because when I run only a method or a class work's fine, but when I run a androidTest folder some mocks doesn't work.

My dagger2 configuration is fine, with `Subcomponents`, using latest DaggerMock and Dagger2 versions.

You can have a look [my repository](https://github.com/tonilopezmr/Game-of-Thrones) and run only `DetailActivityTest` and before run all `androidTest` folder.

**Comment by plastiv** [comment]
@tonilopezmr Since android Application is singleton, you need to reset its state for every test.
Here: https://github.com/tonilopezmr/Game-of-Thrones/blob/master/app/src/main/java/es/npatarino/android/gotchallenge/GotChallengeApplication.java#L49
You are caching `characterComponent` instance, through effectively using `Component` which was created by the first test. 

Instead, you need to create new instance for every test. For example, reset reference to null at `@After`.

**Comment by tonilopezmr** [comment]
@plastiv I will try, but, DaggerMockRule is reset before each test, right?

**Comment by tonilopezmr** [comment]
Oh good, @plastiv that's right.

I following [this post](http://frogermcs.github.io/dependency-injection-with-dagger-2-custom-scopes/) to right dagger2 scope way.

**Comment by plastiv** [comment]
DaggerMockRule will create new instance of the component for every test method (with new mock dependency instances), but your code should not cache it. And its yours responsibility to reset it. That's why devs hate singletons ;)

**Comment by tonilopezmr** [comment]
@plastiv Right 

![](https://media.tenor.co/images/31f564ba739497057bc76f093eeedad2/raw)
