### ISSUE TITLE
Subcomponent from ActivityComponent and AppComponent

### ISSUE THREAD

**Issue by Michi1209** [fabioCollini/DaggerMock#24]
Hi @fabioCollini .
First of all really nice feature and I really appreciate your work.
I am currently working for Ui testing for a larger app and I've got following Implementation:

```

    @Singleton
    @Component(modules = AppModule.class)
    public interface AppComponent {

        void inject(MyApp app);
        //other injections an provides for Object used during the lifecycle of app
}
```

then I have the module for the app with the context

```
@Module
public class AppModule {

    private Context mAppContext;

    public AppModule(Context appContext) {
        this.mAppContext = appContext.getApplicationContext();
    }

    @Singleton
    @Provides
    public Context provideAppContext(){
        return mAppContext;
    }
//other provides implementations from component
```

then I have an ActivityComponent for the component during the lifecycle of one activity

```
@PerActivity
@Component(dependencies = AppComponent.class, modules = ActivityModule.class)

public interface ActivityComponent {

void inject(BaseActivity activity);

//some injections and 2 provide functions

AppCompatActivity activity();

InfoComponent plus(InfoModule module);    

 Component2 plus(Module2 module);

//some more components and module dependencies
}
```

and the activity module is just

```
@Module
public class ActivityModule {
    private final AppCompatActivity activity;

    public ActivityModule(AppCompatActivity activity) {
        this.activity = activity;
    }

    @Provides @PerActivity public AppCompatActivity activity() {
        return this.activity;
    }
    //the 2 providers
```

then i have implemented my components as following:

```
@PerActivity
@Subcomponent(modules = InfoModule.class)
public interface InfoComponent {
    void inject(DetailActivity activity);
}
`
with the module
`@Module
public class InfoModule {

    @Provides
    DetailPresenter provideDetailPresenter(ShowDetailsUseCase showDetailsUseCase,
                                           GetPoisUseCase getPoisUseCase,
                                           AccountManager accountManager, Navigator
                                                   navigator) {
        return new DetailPresenter(showDetailsUseCase, getPoisUseCase, accountManager, navigator);
    }
}
```

in my DetailActivity the DetailPresenter is a field annotaded with @Inject.

```
public class DetailActivity extends BaseActivity implements DetailView {


    @Inject
    DetailPresenter mPresenter;

    InfoComponent mComponent;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mComponent = getActivityComponent().plus(new InfoModule());
        mComponent.inject(this);
        mPresenter.onCreate(new PresenterBundle(getIntent().getExtras(), savedInstanceState));
    }
```

the DetailPresenter then is created with the provides method in InfoModule. The DetailPresenter looks like this: 

```
@Inject
    public DetailPresenter(ShowDetailsUseCase getDetailsUseCase, GetPoisUseCase getPoisUseCase,
            AccountManager
            accountManager, Navigator navigator) {
        this.mDetailsUseCase = getDetailsUseCase;
        this.getPoisUseCase = getPoisUseCase;
        this.accountManager = accountManager;
        this.navigator = navigator;
    }

```

and the showDetailsUseCase and GetPoisUseCase use Constructor Injection aswell.

Now my question is how I mock these components with your rule:
I already tried creating test Components and Modules for App, Activity and Info 

```
@Rule
public final DaggerMockRule<TestAppComponent> componentDaggerMockRule =
            new DaggerMockRule<TestAppComponent>(TestAppComponent.class, new TestAppModule(getApp()))
                    .set(component -> getApp().setAppComponent(component);
```

but then my TestActivityModule does not get used because it gets injected in the baseActivity onCreate method.
Then i tried:

```
@Rule
    public final ActivityTestRule<DetailActivity> main = new ActivityTestRule<DetailActivity>(DetailActivity.class, false, false);

@Rule
public final DaggerMockRule<TestActivityComponent> activityComponentDaggerMockRule =
            new DaggerMockRule<TestActivityComponent>(TestActivityComponent.class, new TestActivityModule(main.getActivity()))
                    .set(testActivityComponent -> {
                        component=testActivityComponent.plus(new TestInfoModule());
                        activityComponent=testActivityComponent;
                        component.inject(DetailActivityTest.this);
                    })
                    .set(TestComponent.class, testComponent -> {
                        getApp().setAppComponent(testComponent);
                    }).addComponentDependency(TestComponent.class, new TestModule(getApp()));
```

but main.getActivity of my ActivityTestRule is still null when creating the rule and my mocked InfoModule doesn't get used. 
Do you have any Idea how I can fix my problem. The thing is cannot mock ShowDetailsUseCase and getPoisUseCase because they are annotated with @Inject constructors and then an this error occurs: 

You must define overridden objects using a @Provides annotated method instead of using @Inject annotation

Thank you in advance

**Comment by fabioCollini** [comment]
Hi,
the error you get is because of the internal implementation of DaggerMock, it creates a module subclass to override some methods so it's not possible to override objects created using @inject annotation.
Can you try to create the object you want to override in a module?
In this module https://github.com/fabioCollini/DaggerMock/tree/master/RealWorldApp you can find an example similar to the one you are using.

**Comment by Michi1209** [comment]
The problem is that I have an Activity component that is injected in the activity and my subcomponents are dependent on the activity component. I cannot overwrite this activity component because it is injected in the onCreate method. 

Now i decided to try something else by mocking the data layer. There I have another problem:
I use Dao's(https://en.wikipedia.org/wiki/Data_access_object) to get Data from my local storage.

```
public class InfoEntityDao {

    @Inject
    public InfoEntityDao(){

    }

    public InfoEntity getEntityById(long entityId, Class entityClass) {
        //get entity from local database storage...
    }
}
```

now the problem is that i have an Inject constructor, so I cannot mock or spy this object.
Do you have any Idea how to solve this?

**Comment by fabioCollini** [comment]
Hi, I am sorry but you can't override the dao if you define it using Inject annotation. You must create a provide method inside a module, in this way DaggerMock will create a subclass of this module returning the mock instead of the real object.
