### ISSUE TITLE
Mocking internal services

### ISSUE THREAD

**Issue by mattinger** [fabioCollini/DaggerMock#28]
I have a module which creates a bunch of service objects, and then those are used to contruct some manager objects:

```
@Provides
@Singleton
public TokenStore provideTokenStore(final SharedPreferences sharedPreferences) { ... }

@Provides
@Singleton
public LoginManager provideLoginManager(final TokenStore tokenStore) { ... }
```

NOTE:  These two objects are actually in two different modules, as my data/http layer is separated from my business logic (which allows me to have an offline demo mode as well).

I tried inserting a mock version of TokenStore in my test class:

```
@Mock
TokenStore tokenStore;
```

While this replaces the TokenStore that's exposed via @Inject, this seems to happen
outside of the actual module itself.  So within the module, the TokenStore that's given to the
LoginManager is the real instance, and not the mocked one.

Is there any way to solve this issue, and allow the mock TokenStore to be used as dependencies within a module?

**Comment by fabioCollini** [comment]
Hi, this example should work. Are you passing both modules when you create the rule?
Are you using it in an open source project? Or can you create a small example to reproduce it?
Thanks for you report

**Comment by mattinger** [comment]
I think this may have had to do with the activity rule auto launching.  I have since made it a manual launch of the activity, and it worked.  However, i also struggled alot to get things compiled due to dependencies on dexmaker and some proguard rules that were needed.

```
  androidTestCompile 'com.github.fabioCollini:DaggerMock:0.6.2'
  androidTestCompile 'com.google.dagger:dagger:2.1'
  androidTestCompile "com.github.crittercism.dexmaker:dexmaker-parent:$dexmakerVersion"
  androidTestCompile "com.github.crittercism.dexmaker:dexmaker-mockito:$dexmakerVersion"
  androidTestCompile "com.github.crittercism.dexmaker:dexmaker-dx:$dexmakerVersion"
  androidTestCompile "com.github.crittercism.dexmaker:dexmaker:$dexmakerVersion"
  androidTestCompile 'javax.inject:javax.inject:1'
  testCompile 'com.github.fabioCollini:DaggerMock:0.6.2'
  testCompile 'com.google.dagger:dagger:2.1'
  testCompile "com.github.crittercism.dexmaker:dexmaker-parent:$dexmakerVersion"
  testCompile "com.github.crittercism.dexmaker:dexmaker-mockito:$dexmakerVersion"
  testCompile "com.github.crittercism.dexmaker:dexmaker-dx:$dexmakerVersion"
  testCompile "com.github.crittercism.dexmaker:dexmaker:$dexmakerVersion"
  testCompile 'javax.inject:javax.inject:1'
```

```
ext {
  dexmakerVersion = 'b0ac1c73a9530909a5ad4cbe03859e11eada0b06'
}
```
