### ISSUE TITLE
Mockito's Default Answer is never called in ModuleOverrider

### ISSUE THREAD

**Issue by danielocampo2** [fabioCollini/DaggerMock#30]
Hi, I've been fighting with this issue for quite a long time now but I cannot seem to find the solution to it.
The problem is that the Mocked Modules are not providing mocked dependencies and instead providing the real class. I can assure that the modules are actually the mocked modules. Debugging to get to the root of the issue, I found out that the defaultAnswer defined in ModuleOverrider is never being called for any of my mocked modules, while it is being correctly called in the ComponentOverrider.
Does that make sense?
Do you have any idea of why this could be happening? 
Do you think it might have anything to do with our Dagger 'architecture'? (I see that it is different from the example)

Here I attach the code related to the issue.

This is my test class:

```
public class MyTest {
@Rule
    public ActivityTestRule<PasswordLoginActivity> mActivityTestRule = new ActivityTestRule<>(PasswordLoginActivity.class, false, false);

    @Rule public final DaggerMockRule<ApplicationComponent> daggerRule = new DaggerMockRule<>(ApplicationComponent.class, new AppModule(), new LoginModule())
            .addNoMockModules(new AndroidModule(getApp())
            .set(new DaggerMockRule.ComponentSetter<ApplicationComponent>() {
                @Override public void setComponent(ApplicationComponent component) {
                    getApp().setDaggerTestComponent(component);
                }
            });

    private MyApplication getApp() {
        return (MyApplication) InstrumentationRegistry.getInstrumentation().getTargetContext().getApplicationContext();
    }

    @Mock LoginAnalyticsReporter lAnalyticsReporter;
    @Mock AnalyticsReporter analyticsReporter;
    @Mock PasswordLoginPresenter passwordLoginPresenter;

    @Test
    public void loginSuccessfulTest() {
        Mockito.doNothing().when(lAnalyticsReporter).loginButtonClicked();
        
        mActivityTestRule.launchActivity(null);

        // All Espresso interactions within the Login Screen

    }
}
```

And this are the modules that are related to this dependencies:

```
open class AppModule {

  @Provides
    @Singleton
    fun providePasswordLoginAnalyticsReporter(analyticsReporter: AnalyticsReporter)
            : AppAnalyticsReporter =
            AppAnalyticsReporterImpl(analyticsReporter)

  @Provides
    @Singleton
    fun provideAnalyticsReporting(): AnalyticsReporter = FirebaseAnalyticsReporter()

  // More provide methods ...

}
```

```
open class LoginModule {

    @Provides
    @Singleton
    fun providePasswordLoginAnalyticsReporter(
                    /* many other depedencies */
analyticsReporter: AnalyticsReporter)
            : LoginAnalyticsReporter =
            LoginAnalyticsReporterImpl(analyticsReporter)

    @Provides
    @Singleton
    fun providePasswordLoginPresenter(
                                      loginAnalyticsReporter: LoginAnalyticsReporter)
            : PasswordLoginPresenter =
            PasswordLoginPresenterImpl(
                    /* many other depedencies */
                    loginAnalyticsReporter)

}
```

And this is our DaggerComponent:

```
@Singleton
@Component(modules = arrayOf(
        LoginModule::class,
        AppModule::class,
        /* many other modules */
))
interface ApplicationComponent :
        /* many other injectors, implemented in our Application object */
        LoginInjector,
        AppInjector
       {

    fun inject(application: MyApplication)
    fun inject(target: MainActivity)
}
```

So to be clear, the LoginAnalyticsReporter provide method receives the real AnalyticsReporter implementation and the PasswordLoginPresenter ends up receiving the real LoginAnalyticsReporter, instead of receiving the mocked ones.
But in my test class, if I use the mock objects, they will be the mocked ones, so any call to mockito's methods to change what they do or return will be pointless.

Thanks a lot for your help and let me know if I need to clarify something else!

**Comment by fabioCollini** [comment]
Hi, the defaultAnswer of ModuleOverrider should be invoked. How many components are you using in your project?
Have you implemented the `addNoMockModules` in your fork? Which error do you get if you don't use that method?

**Comment by danielocampo2** [comment]
Hi, we are using just one component, and if it's of any help, we have some
modules that just act as containers of other modules and don't have any
provide methods (but in my test I'm not using any of these, just simple
modules).
I implemented the addNoMockModules, that is basically another list of
modules that are built in initComponent but using the provided module
object directly without passing through ModuleOverrider to ensure they're
not mocked. Does that sound right? This seems to work fine as the
dependencies of this module are provided correctly.
The error that I was getting by adding the module directly is that the
class variable that is passed as parameter in the constructor - new
Androidmodule(getApp()) - is Null when any of the provide methods of that
class is invoked. I understand this should work as your example has a
similar module, but so far couldn't make it work.
Tried your RealWorldApp and works just fine.

Let me know if you any idea or need any other information.
Thank a lot.


On 29/01/2017 7:16 AM, "Fabio Collini" <notifications@github.com> wrote:

Hi, the defaultAnswer of ModuleOverrider should be invoked. How many
components are you using in your project?
Have you implemented the addNoMockModules in your fork? Which error do you
get if you don't use that method?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fabioCollini/DaggerMock/issues/30#issuecomment-275864585>,
or mute the thread

**Comment by fabioCollini** [comment]
I think I have found the problem, it's related to Kotlin. You have defined the module as open but the provide methods are not open. So Mockito can't override these methods and the real object is used. Can you try to define the methods as open?
In the next days I am going to add a check to throw an exception when the test contains a field that is created using a final provide method.
Thanks again for your report!

**Comment by danielocampo2** [comment]
Oh, man, I knew it was going to something so... simple like this. Thanks a lot for taking the time to find the issue. The bright side for me is that at least now I know a lot of the internals of your great library haha.
That exception would be great, especially now with Kotlin usage raising.

Thanks again! You can close this if you think there's nothing else to say about it.

**Comment by fabioCollini** [comment]
I have committed the check to throw an exception on final methods, you can try it using the commit hash `59af954ba3` as version in your build.gradle file.
I think that the also other bug you report is related to this problem, can you try to define all the methods open and remove the invocation to `addNoMockModules` method?

**Comment by danielocampo2** [comment]
Great, Thanks.
Yes, effectively, I tried that and that error was related to this issue so
no need of the noMockModules.
