### ISSUE TITLE
Inheritance Support

### ISSUE THREAD

**Issue by rpattabi** [fabioCollini/DaggerMock#33]
If mocks and injections are repeated, I like to extract it to a base class. This way, I can repeat same dependencies for other tests without having to repeat. For example:

```
public abstract class ActivityTest {
    @Rule
    public final MyDaggerMockRule daggerMockRule = new MyDaggerMockRule();

    @Mock
    protected DependencyA mockDependencyA;

    @Named("s1") 
    protected String s1 = "test_string_s1";
    
    @Named("s2")
    @InjectFromComponent
    protected String s2;
}

@RunWith(AndroidJUnit4.class)
@LargeTest
public class AnActivityTest extends ActivityTest {

    @Rule
    public ActivityTestRule<AnActivity> activityTestRule =
            new ActivityTestRule<>(AnActivity.class, true, false);

    @Mock
    DependencyB mockDependencyB;

    @Named("s3")
    @InjectFromComponent
    protected String s3;
    ...
}
```

Is this supposed to work already? I noticed that we get main app dependencies instead of the ones from defined in the test, particularly in the base class.

PS: This library saves me a lot of headache. Thank you.

**Comment by fabioCollini** [comment]
Hi, it wasn't supposed to work but it's not difficult to add the support. I have already committed the new version, you can try it using the commit `59020907c0` as version in your gradle file.
Thanks for the suggestion!

**Comment by rpattabi** [comment]
@fabioCollini It works fine. Thanks for quickly fixing this.

**Comment by rpattabi** [comment]
@fabioCollini It works fine for `@Mock` annotation. I think it doesn't work for `@InjectFromComponent` annotation. Could you check?

**Comment by fabioCollini** [comment]
You are right, I added the support for `@InjectFromComponent` annotated fields in base class in commit `fe0c164dad`. I'll release a new version soon.
Thanks again for your report

**Comment by rpattabi** [comment]
Works fine..
