### ISSUE TITLE
[Android] Mock activity scoped dependencies.

### ISSUE THREAD

**Issue by carlosmuvi** [fabioCollini/DaggerMock#35]
First of all, congrats! This library has saved me a lot of trouble and made my life easier 😄 

I'm having some issues trying to mock a dependency living in an activity component. Since I'm injecting the dependencies in the activity during `onCreate`, when the `DaggerMockRule` gets executed and tries to perform the injection, the activity has not been generated by the activityTestRule, so I get a `java.lang.NullPointerException: Cannot inject members into a null reference`:

```java
@Rule
public TuroTestRule<CreditCardActivity> activityTestRule = new TuroTestRule<>(CreditCardActivity.class, true, false);

@Rule public DaggerMockRule<CreditCardComponent> daggerMockRule =
    new DaggerMockRule<>(CreditCardComponent.class, new CreditCardModule())
        .addComponentDependency(MainApplicationComponent.class,  new ApplicationModule(getApp()), new SingletonRepositoriesModule())
        .set(component -> component.inject(activityTestRule.getActivity()));

@Mock PaymentDataContract.Repository mockPaymentRepository;
```

This is my simplifided structure:

Activity
----

```java 
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_payment_method);
    ButterKnife.bind(this);
    getComponent().inject(this);
    presenter.doSomething();
}

@Override
public CreditCardComponent getComponent() {
    return DaggerCreditCardComponent.builder()
        .mainApplicationComponent(getApplicationComponent())
        .build();
}
```

Component
----

```java
@ActivityScope @Component(dependencies = {MainApplicationComponent.class}, modules = {CreditCardModule.class})
public interface CreditCardComponent {
    void inject(CreditCardActivity activity);

    CreditCardContract.Presenter presenter();
    PaymentDataContract.Repository repository();

}
```

Module
----
```java
@Module
public class CreditCardModule {

    public CreditCardModule() {
    }

    @Provides
    public CreditCardContract.Presenter providesPresenter(
            CreditCardPresenter creditCardPresenter) {
        return creditCardPresenter;
    }

    @Provides
    public PaymentDataContract.Repository providesPaymentRepository(PaymentRepository repository) {
        return repository;
    }
}
```
What would be in your opinion the ideal architecture for this?

Thank you in advance!

**Comment by fabioCollini** [comment]
Hi, is there a reason why you are using a component dependency instead of a SubComponent? This is an [example](https://github.com/fabioCollini/DaggerMock/tree/master/RealWorldApp/src/main/java/it/cosenonjaviste/daggermock/realworldapp) using SubComponent.
In your example activity reference is null because the rule is created before the activity, I am not sure you can do something similar event if you can obtain the activity. There is something strange, you are trying to do two Activity injections (the first in the onCreate with the real component and another in the test).

**Comment by athkalia** [comment]
@carlosmuvi I just integrated this library into my open source project https://github.com/athkalia/Just-Another-Android-App that demonstrates how to do exactly what you are asking about.
@fabioCollini My open source library provides a decent robolectric example in a bit bigger project, feel free to showcase it if you want to. Example is in MainActivityTest class

**Comment by fabioCollini** [comment]
@athkalia I added a link in the readme, many thanks for integrating DaggerMock in your project!

**Comment by sergiomarquesmoura** [comment]
@carlosmuvi did you end up with a solution for this? Couldn't really find the example that @athkalia was talking about

**Comment by athkalia** [comment]
I ended up removing the library when i moved to the 2.12 version of dagger with android specific support, a couple of months ago. @fabioCollini It's probably worth removing the reference
