### ISSUE TITLE
How to provide mocked named dependency?

### ISSUE THREAD

**Issue by plastiv** [fabioCollini/DaggerMock#36]
We are using DaggerMock rule because of convenience of declaration field, which is injected then into dependency graph. With named dependencies, I would expect next api possible

```
public class MainServiceTest {

    @Rule public final DaggerMockRule<MyComponent> rule = new DaggerMockRule<>(MyComponent.class, new MyModule());

    @Mock RestService restService;

    @Mock @Named("mykey") MyPrinter myPrinter;

    @InjectFromComponent MainService mainService;

    @Test
    public void testDoSomething() {
        when(restService.getSomething()).thenReturn("abc");

        mainService.doSomething();

        verify(myPrinter).print("ABC");
    }
}
```

But it doesn't work after upgrading from `0.6.3 to 0.6.4`. `@Named` fields are not replaced at the graph. 

Would you consider such api as valid feature request?

**Comment by fabioCollini** [comment]
It depends how you define MyPrinter in the module, if you define it using the same Named annotation it should work. [Here](https://github.com/fabioCollini/DaggerMock/blob/master/lib/src/test/java/it/cosenonjaviste/daggermock/named/NamedTest.java) you can find a test that verify this behavior.

**Comment by plastiv** [comment]
Thank you for quick reply. 

I checked the sample and it worked. Then I get back to my project and turned out issue was not with DaggerMock :man_facepalming: Sorry for taking you time.
