### ISSUE TITLE
Subcomponent with builder support.

### ISSUE THREAD

**Issue by Pedramrn** [fabioCollini/DaggerMock#38]
`AppComponent.java`
```java
@Component(modules = AppModule.class)
public interface AppComponent {
    MainComponent.Builder plus();
}
```
`MainComponent.java`

```java
@Subcomponent(modules = MainModule.class)
public interface MainComponent {
    void inject(ActivityMain activity);

    @Subcomponent.Builder
    interface Builder {
        Builder mainModule(MainModule module);

        MainComponent build();

    }

}
```

Is there a way to mock this?

**Comment by fabioCollini** [comment]
It depends, what do you want to mock? Which test do you want to write?
It works if you want to mock an object defined in the `AppComponent`, I am working to fix an issue when the mock is defined in the `MainComponent` and when the `InjectFromComponent` annotation is used.

**Comment by Pedramrn** [comment]
I have dependencies in both components, I tried to mock the `AppComponent` only, but it failed with an reflection error method not found, with name `mainModule` and arg `MainModule`.

**Comment by fabioCollini** [comment]
I have just pushed a fix to support subcomponent builders, can you please try to use the snapshot version [cb9ba069e5](https://jitpack.io/#fabioCollini/DaggerMock/cb9ba069e5)?
Thanks for your report!

**Comment by carlosmuvi** [comment]
I'm having the same problem, even using the snapshot version. I'm also using the dagger2 android injector helper classes.

```java
@Component(modules = {
    ApplicationModule.class,
    ActivityBindingModule.class,
    AndroidSupportInjectionModule.class})
public interface MainApplicationComponent extends AndroidInjector<MainApplication> {

    @Component.Builder
    abstract class Builder extends AndroidInjector.Builder<MainApplication> {

        abstract Builder applicationModule(ApplicationModule applicationModule);
        @Override public abstract MainApplicationComponent build();
    }
}
```
I'm getting a method not found error.

`java.lang.NoSuchMethodException: applicationModule [class com.relayrides.android.relayrides.di.components.MainApplicationComponent$ApplicationModule]`

**Comment by fabioCollini** [comment]
I haven't tested yet injector class support in DaggerMock. Which Dagger version are you using? Are you using a junit or an espresso test? Could you provide an example?
Thanks for your report

**Comment by fabioCollini** [comment]
I have pushed a new version to support Dagger Android (you can try it using version [0.7.1-beta1](https://jitpack.io/#fabioCollini/DaggerMock/0.7.1-beta1)). In this version Dagger Android is supported in Espresso test to replace objects defined in Application component, I'll continue to investigate to find a way to support it in JUnit tests and for subcomponents and dependent components.
