### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by mrsasha** [fabioCollini/DaggerMock#4]
Hi,

I just used the library in my app tests and it works great. I was just wandering if there are any plans for Kotlin support? At the moment, when putting the `@Mock` annotation, it still complains that the variable is not initialized.

Thanks!

**Comment by fabioCollini** [comment]
Hi, I am sorry but I am not (yet!) using Kotlin. Is there the same issue in Mockito? Have they solved this issue?

**Comment by mrsasha** [comment]
Mockito generally works with Kotlin, at least the things that I tried (`Mockito.mock(T::class.java)`, `Mockito.verify(mock)`, I'm not really an expert). It's just that gradle has an issue with the `@Mock` annotation, it doesn't recognize it as something that sets the value, so when I use it like this:

```@Mock
    internal var translationManager: TranslationManager```

I get the `property must be initialized or abstract` error.

**Comment by mrsasha** [comment]
Oh, wait, sorry, I see what you mean, @Mock is actually part of the Mockito, I thought you were doing some rewriting there. My bad. :)
