### ISSUE TITLE
Real classes always used in test instead of mocks

### ISSUE THREAD

**Issue by jbmlaird** [fabioCollini/DaggerMock#40]
I've been reading about this library all day but have been unable to get an implementation working. Whenever I run my `MainActivityTest` it will always create a new instance of `MainPresenter` and not use my `Mock`. What am I doing wrong? I feel I have copied your example almost exactly.

The test file is [here](https://github.com/jbmlaird/DaggerMockRepository/blob/master/app/src/androidTest/java/bj/daggermockexperiment/MainActivityTest.java) and you can see the rest in the repository.

Sorry for opening an issue. I thought it would be quicker than a SO question.

**Comment by jbmlaird** [comment]
I managed to get it working by adding the DaggerMock library as a module and adding

`androidTestCompile project(':daggermock')`

to my `build.gradle`. Surprised no one else has this issue so there must have been a problem with my implementation

**Comment by fabioCollini** [comment]
I already fixed this error but it wasn't available yet in version 0.6.4. I have release version 0.6.5 now, you can use it instead of including the module directly.

**Comment by jbmlaird** [comment]
Confirmed. Thanks @fabioCollini
