### ISSUE TITLE
Static Module / Method Support

### ISSUE THREAD

**Issue by 51systems** [fabioCollini/DaggerMock#46]
Newer version of dagger (2.10, 2.11 and maybe earlier) encourage the pattern of defining dependencies as static methods in modules. Modules that only have static dependencies aren't injected into the builder https://google.github.io/dagger/unused-modules

As a workaround I'm re-defining modules I want to mock with non-static methods, but I was wondering if there were any plans to support this case down the road.

**Comment by fabioCollini** [comment]
Hi, with the current implementation of DaggerMock it's not possible to support modules static methods. There isn't a plan to support them yet, maybe it could be possible using PowerMock or something similar but it's not easy to implement it.
