### ISSUE TITLE
@ContributesAndroidInjector module support

### ISSUE THREAD

**Issue by p4r4n01d** [fabioCollini/DaggerMock#47]
I am using the dagger2 android injector helper classes and would like to provide mocks of some objects in the ApplicationModule (not shown). However, the module is abstract as dagger generates the activity injector code so I cannot create an instance of the module in my mock TestRule to call the constructor of DaggerMock. Is there a way to mock this without adding an extra subcomponent?

```ApplicationModule.java```
```
@Module
@SuppressWarnings("WeakerAccess")
public abstract class ApplicationModule {

    @PerActivity
    @ContributesAndroidInjector(modules = ActivityModule.class)
    abstract BaseActivity contributeBaseActivityInjector();

...
}
```

Here is my application component, which uses a builder

```ApplicationComponent.java```
```
@Singleton
@Component(modules = {ApplicationModule.class, AndroidInjectionModule.class})
public interface ApplicationComponent {

    @Component.Builder
    interface Builder {
        @BindsInstance
        Builder application(TheApplication app);
        ApplicationComponent build();
    }
```

Here is the application class.

```TheApplication.java```
```
public class TheApplication extends Application implements
        HasActivityInjector {

    @Inject
    DispatchingAndroidInjector<Activity> mDispatchingAndroidInjector;

    private ApplicationComponent mApplicationComponent;

    @Override
    public void onCreate() {
        super.onCreate();
        getComponent().inject(this);
    }

    @Override
    public DispatchingAndroidInjector<Activity> activityInjector() {
        return mDispatchingAndroidInjector;
    }

    public ApplicationComponent getComponent() {
        if (mApplicationComponent == null) {
            mApplicationComponent = DaggerApplicationComponent.builder()
                    .application(this)
                    .build();
        }
        return mApplicationComponent;
    }
}
```

**Comment by fabioCollini** [comment]
DaggerMock can override only not abstract modules and `ContributesAndroidInjector` are not supported. But you can try to create a new module (not abstract) with the objects you want to override.

**Comment by RoRoche** [comment]
Does DaggerMock support the new dagger-android library?

**Comment by fabioCollini** [comment]
@RoRoche the new dagger-android library is not supported in current version but I am working to support it (at least for replacing objects defined in application component). I hope I'll release a new release soon.

**Comment by j2emanue** [comment]
@RoRoche could you give me a link to the new dagger library your referring to. Maybe i can help

**Comment by RoRoche** [comment]
@j2emanue https://google.github.io/dagger/android.html

**Comment by j2emanue** [comment]
I've been using it with goggles dagger2 . I't seems ok
________________________________

**Comment by fabioCollini** [comment]
I have pushed a new version to support Dagger Android (you can try it using version [0.7.1-beta1](https://jitpack.io/#fabioCollini/DaggerMock/0.7.1-beta1)). In this version Dagger Android is supported in Espresso test to replace objects defined in Application component, I'll continue to investigate to find a way to support it in JUnit tests and for subcomponents and dependent components.
