### ISSUE TITLE
How to mock modules that uses @Binds provider?

### ISSUE THREAD

**Issue by RomainPiel** [fabioCollini/DaggerMock#51]
So it looks like DaggerMock mocks the modules that are passed during initialisation. But how to do that with `abstract` and `interface` modules? If we use modules [defined like that](https://google.github.io/dagger/faq.html#why-is-binds-different-from-provides):

```java
  @Module
  interface MyModule {
    @Binds Something bindSomething(SomethingImpl something);
  }
```

Then we can't create an instance of that and pass it to the rule.

Any way to mock this kind of modules?

**Comment by fabioCollini** [comment]
I am sorry by `abstract` and `static` methods in modules are not supported by DaggerrMock (and cannot be supported because of the DaggerMock implementation).
You can still use them in a separate module to define objects that you won't replace in tests.
