### ISSUE TITLE
Support @Module(includes = ...)

### ISSUE THREAD

**Issue by philipesteiff** [fabioCollini/DaggerMock#54]
Hi Fabio,

Would be nice if DaggerMock had `@Module(includes = OtherModule)` support.

For example:

```
@Singleton
@Component(
    modules = arrayOf(
        AndroidInjectionModule::class,
        AppModule::class,
    )
)
interface ApplicationComponent
```

``` 
@Module(includes = arrayOf(
    RepositoryModule::class /* I would like to mock this module */
))
class AppModule 
```
In Version 0.7.1-beta1 didn't work :(

**Comment by fabioCollini** [comment]
Hi, I tried to reproduce this case and it works (even if I have never tested it before!).
You must pass both modules in the DaggerMockRule constructor, you can find an example here: https://github.com/fabioCollini/DaggerMock/tree/master/daggermock/src/test/java/it/cosenonjaviste/daggermock/moduledependency

Let me know if it works in your example.
