### ISSUE TITLE
 @InjectFromComponent being called too late

### ISSUE THREAD

**Issue by j2emanue** [fabioCollini/DaggerMock#58]
Hi, when i try to use object injected with  @InjectFromComponent annotation  it seems its not ready yet until right when my espresso test method is invoked. i tried using it in setup (@Before annotation) but its not working.  it returns null at that point. can you make it inject sooner in the testing life cycle ?

**Comment by fabioCollini** [comment]
How are you creating the ActivityTestRule? Usually to fix issues like this you just need to pass `false` to `launchActivity` constructor argument.

**Comment by j2emanue** [comment]
Does InjectFromComponent give me a real object or a mock?
________________________________

**Comment by fabioCollini** [comment]
A real object, usually this annotation is used in JVM tests to obtain the real object to test
