### ISSUE TITLE
Mocking Dagger subcomponents

### ISSUE THREAD

**Issue by sergiomarquesmoura** [fabioCollini/DaggerMock#6]
Hi, 

I am trying to setup a **DaggerMockRule\<UserComponent\>** where UserComponent is a @Subcomponent. Due to that, there isn't a DaggerUserComponent being generated, and my test fails because it cannot find **DaggerUserComponent**.

Is it possible to apply rules to Subcomponents ?

**Comment by fabioCollini** [comment]
Hi, looking at the generated code it seems that subcomponents are not flexible as normal components. They are created in generated class:

    @Override
    public MySubComponent mySubComponent() {  
      return new MySubComponentImpl();
    }

MySubComponentImpl is generated, it creates the module in the constructor:

    private final class MySubComponentImpl implements MySubComponent {
      private final MyModule2 myModule2;
    
      private MySubComponentImpl() {  
        this.myModule2 = new MyModule2();
        initialize();
      }
    
      private void initialize() {  
      }
    
      @Override
      public MainService mainService() {  
        return DaggerMyComponent.this.mainServiceProvider.get();
      }
    }

And the module must contain a constructor with no parameters.

So I think that unfortunately DaggerMock cannot be used to override objects in subcomponents. :( But I have never used subcomponents in real projects, any ideas how to implement it are welcome.

**Comment by sergiomarquesmoura** [comment]
Yeah, I understood that in order to use DaggerMock we can't count on subcomponents. Or at least mock them. Thank you!

**Comment by fabioCollini** [comment]
Hi, I have found a way to support Subcomponents! You can find more info in the README and a new demo project that uses subcomponents.

**Comment by j2emanue** [comment]
in the read me file can you give an example on how to use the subComponent. I see you explain how to declare it in parent component but not how to use it with daggerMock.
