### ISSUE TITLE
Cannot replace objects which is not created in a module 

### ISSUE THREAD

**Issue by sborphukon** [fabioCollini/DaggerMock#62]
Hi,
I am using your lib is there any way to replace objects  which was not created in a module but is directly injected through constructors.

https://stackoverflow.com/questions/39612311/android-test-with-dagger-mock-inject-constructor/47477980#47477980

**Comment by fabioCollini** [comment]
Hi, DaggerMock creates a module subclass to replace production objects. So I am sorry but it's not possible to replace objects created outside a module.
