### ISSUE TITLE
Inject into Android espresso test, using dagger-android

### ISSUE THREAD

**Issue by dweebo** [fabioCollini/DaggerMock#67]
I see there is some support for dagger-android https://github.com/fabioCollini/DaggerMock/issues/47

I'm trying to inject objects into my espresso test but I can't figure out if it's possible or how to do it.  I tried modifying AndroidInjectorActivityTest like this:

```
public class AndroidInjectorActivityTest {

    @Rule
    public EspressoDaggerMockRule rule = new EspressoDaggerMockRule();

    @Rule public ActivityTestRule<AndroidInjectorActivity> activityRule = new ActivityTestRule<>(AndroidInjectorActivity.class, false, false);

    @Mock
    RestService restService;

    @InjectFromComponent
    SnackBarManager snackBarManager;
```

but the `@InjectFromComponent` does not work.

**Comment by fabioCollini** [comment]
Hi,
I tried to modify `AndroidInjectorActivityTest` adding `InjectFromComponent` annotation and it works. But you must add also a method in the component that returns a `SnackBarManager`, using `InjectFromComponent` you can use only objects exposed directly by the component.

**Comment by CAH-peterhewitt** [comment]
Yes that works, thanks so much for the quick reply!

**Comment by dweebo** [comment]
Thanks that worked!
