### ISSUE TITLE
Mocking service from abstract modules

### ISSUE THREAD

**Issue by Dunemaster** [fabioCollini/DaggerMock#68]
Hello!
Can I mock services coming from abstract modules (@Binds) ?

**Comment by fabioCollini** [comment]
No, sorry but abstract modules are not supported. But if you have multiple modules (some abstract and other not abstract) you can use DaggerMock to replace objects defined in the not abstract modules.

**Comment by Dunemaster** [comment]
Thank you for clarification. Maybe it should be mentioned  in README
Are there any plans to add support for abstract modules?
They are a popular dagger feature, being more efficient and consice than non-abstract ones

**Comment by fabioCollini** [comment]
No, I am sorry unfortunately it's not possible to support them because of DaggerMock implementation.
You are right, I'll update the readme soon to specify Dagger features that are supported.
