### ISSUE TITLE
Example when extending from DaggerApplication 

### ISSUE THREAD

**Issue by Tulioh** [fabioCollini/DaggerMock#73]
Hello.

Do you guys have one example when I need to set my component to an application that extends DaggerApplication?

Because whenever onCreate is called, DaggerApplication tries to get the component, and at this moment I didn't set the component yet.

**Comment by fabioCollini** [comment]
Hi, this example is similar (the App just implement the `HasActivityInjector` interface but it's similar): 

https://github.com/fabioCollini/DaggerMock/tree/master/RealWorldAppInjector

Or you can take a look at this demo project:

https://github.com/fabioCollini/ArchitectureComponentsDemo

**Comment by Tulioh** [comment]
Thank you!

Please close the issue.
