### ISSUE TITLE
Kotlin version 1.2.41 conflict

### ISSUE THREAD

**Issue by tiagoalmeida92** [fabioCollini/DaggerMock#76]
I'm having some problems when using Kotlin version 1.2.41.

Error on sync
kotlin-stdlib-jre7-1.2.10.jar: kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead

Any way to change daggermock to use Kotlin stdlib jdk7?

**Comment by fabioCollini** [comment]
I am using kotlin 1.2.41 too and I don't get any errors, many other libraries uses an old kotlin version. Can you post all the error and your gradle config?

**Comment by tiagoalmeida92** [comment]
The problems seem to be gone. It probably was another library like you said.
