### ISSUE TITLE
Kotlin EspressoDaggerMockRule and Named injections issue

### ISSUE THREAD

**Issue by mrodriguezcronos** [fabioCollini/DaggerMock#80]
Hello,

Im using Kotlin and Im having trouble trying to make work the DaggerMock rule with Named injections.
I even tried it out on the RealWorldAppKotlin sample. The issue is that the real objects are being used not the mocks.

What Im doing is the following:

MainActivityTest:
Change:
`@Mock lateinit var restService: RestService`
For:
`@Mock @Named("mock") lateinit var restService: RestService`

MainService
Change:
`class MainService @Inject constructor(private val restService: RestService)`
For:
`class MainService @Inject constructor(@Named("mock") private val restService: RestService)`

AppModule:
Change to:
```
@Module
@OpenForTesting
class AppModule(private val app: App) {

    @Provides
    @Singleton @Named("real")
    fun provideRealRestService(): RestService {
        return RestService(app)
    }

    @Provides
    @Singleton @Named("mock")
    fun provideMockRestService(): RestService {
        return RestService(app)
    }
}
```

Thank you for this great library.

**Comment by fabioCollini** [comment]
Hi, I have tried to modify the example and it works. There is just one thing that you need to pay attention to, the field in the test must be annotated in this way:

    @get:Named("mock")

The `get:` is important to annotate the Java getter

**Comment by mrodriguezcronos** [comment]
Well, this is weird. I downloaded the branch with the modifications and ran it as it is, and it still doesn't work for me. 
Since the exact same code is working for you I'm out of ideas on how to keep moving forward with this. Could it be that you see the test is working because of the random on RestService.executeServerCall? You have to run it a few times to be sure.

If you have any more suggestions I would really appreciate it.
Thank you anyway for the library and for your time.

**Comment by fabioCollini** [comment]
Can you try to add the jvmfield annotation? Sorry but I can't try it now and debug the problem, I'll be back in a week

**Comment by mrodriguezcronos** [comment]
I tried both:
```
    @Named("mock") @JvmField
    val restService: RestService = mock()
```
and
```
    @get:Named("mock") @JvmField
    val restService: RestService = mock()
```
Neither one is working.

**Comment by mrodriguezcronos** [comment]
I finally found what was going on, the correct way is with `field:` so it looks like this:
 ```
    @field:Named("mock")
    val restService: RestService = mock()
```

I found the solution [here](https://github.com/google/dagger/issues/761), its also mentioned [here](https://github.com/google/dagger/issues/848) 

I hope this helps someone else too.
Thank you very much @fabioCollini for your assistance.

**Comment by fabioCollini** [comment]
Thanks to you! You created and solve the issue by yourself :)
