### ISSUE TITLE
Dependent Components and Component.Builder

### ISSUE THREAD

**Issue by laenger** [fabioCollini/DaggerMock#83]
Hi,

my current project setup uses (Gradle) feature modules where the `AppComponent` is located in the base feature and each feature has a dependent component that depends on the `AppComponent`. The dependent component support of DaggerMock seems to work here but rather accidental and inefficient. Let me explain and start with the component definitions:

AppComponent:
```java
@Singleton
@Component(modules = [AppModule::class])
interface AppComponent {
    ...
    @Component.Builder
    interface Builder {
        @BindsInstance
        fun application(application: MyApplication): Builder
        fun build(): AppComponent
    }
}
```
Feature1Component:
```java
@Feature1
@Component(modules = [Feature1Module::class], dependencies = [AppComponent::class])
interface Feature1Component {
    ...
    @Component.Builder
    interface Builder {
        fun appComponent(appComponent: AppComponent): Builder
        fun build(): Feature1Component
    }
}
```

The feature builds the component like this:
```java
val feature1Component = DaggerFeature1Component.builder()
    .appComponent(application.appComponent) // <--- difficult
    .build()
```

When setting up mocks for the feature module, I used the hack of passing in the `AppComponent` where usually the modules go
```java
addComponentDependency(Feature1Component::class.javaClass, application.appComponent)
```
This is the only way to customize the component building for dependent components. However, I'd have to rename the builder method to `daggerAppComponent` since DaggerMock is expecting the appComponent class name which is `DaggerAppComponent`. It is also providing a mock which is unnecessary.

It seems that #48 is working around exactly this issue but it doesn't get quite clear there.

Do you have any suggestions about this situation? In a feature module setup, subcomponents are not an option due to the dependency direction. Maybe accepting `customizers` for dependent components?

**Comment by fabioCollini** [comment]
Hi, sorry but I don't get your point and probably it's my fault because it's the second time someone asks this feature :)
Are you trying to override an object defined in the `AppComponent` or in the `Feature1Component`? In the first case it should already work, in the second one I don't think it'll work even using an hack (but I am not sure, maybe I am wrong)

**Comment by laenger** [comment]
Hi,

so first of all you are right, I was jumping to conclusions too early and the "hack" I mentioned doesn't work properly.

I am trying to override objects defined in `Feature1Component`. What fails is building this component. As you can see above, `Feature1Component.Builder` has a required setter `appComponent` (since it depends on `AppComponent`). `addComponentDependency`, however, only calls module setters on the builder and this is not a module setter. So when DaggerMock calls the build method, Dagger complains that appComponent has not been set.

**Comment by laenger** [comment]
I am going to close this issue since I found a solution that works for me: multiple rules. One has to be careful with the order in which rules are executed but this will get easier with JUnit 4.13 and [declarative ordering of rules](https://github.com/junit-team/junit4/wiki/4.13-release-notes#pull-request-1445-and-pull-request-1335-declarative-ordering-of-rules).

```kotlin
@get:Rule
val daggerRule2 = DaggerMock.rule<AppComponent>(AppModule())
        .customizeBuilder<AppComponent.Builder> { it.application(application) }
        .set { component -> application.appComponent = component }
        .providesMock(MyAppDependency::class.java)

@get:Rule
val daggerRule1 = DaggerMock.rule<Feature1Component>(Feature1Module())
        .customizeBuilder<Feature1Component.Builder> { it.appComponent(application.appComponent) }
        .set { component -> application.registerFeatureComponent(..., component) }
        .providesMock(MyFeatureDependency::class.java)
```

Thank you though for looking into this and this great library!

**Comment by fabioCollini** [comment]
Hi, I am happy that you solved but I have a question: how do replace the dependent component in the activity?
And a suggestion: in a multi module project you can try to use daggerAndroid. I am using it and it works really well, you can find an example here: https://github.com/fabioCollini/ArchitectureComponentsDemo

**Comment by laenger** [comment]
Hi, I am using dagger.android, on a feature module level. Replacement is explained towards the bottom of this post. For example, `:feature-one` contains:
```kotlin
@FeatureOne
@Component(modules = [FeatureOneBindingModule::class, FeatureOneModule::class], dependencies = [AppComponent::class])
interface FeatureOneComponent : BaseFeatureComponent, HasFragments {
    @Component.Builder
    interface Builder : BaseFeatureComponent.Builder<FeatureOneComponent> {
        fun featureOneModule(featureOneModule: FeatureOneModule): Builder
        override fun appComponent(appComponent: AppComponent): Builder
    }
}

@Module
abstract class FeatureOneBindingModule {
    @PerFragment
    @ContributesAndroidInjector(modules = [ScreenOneModule::class, ...])
    abstract fun bindScreenOneFragment(): ScreenOneFragment
}
```
`:feature-base` contains:
```kotlin
interface BaseFeatureComponent {
    interface Builder<C> {
        fun appComponent(appComponent: AppComponent): Builder<C>
        fun build(): C
    }
}

interface HasFragments {
    fun fragmentInjector(): DispatchingAndroidInjector<Fragment>
}
```
All feature components are initialized lazily as soon as a feature first needs it. The components are kept inside the Application class and can be used to obtain the corresponding AndroidInjector, which are also cached inside the Application class.
```kotlin
class MyApplication : Application() {
    @get:VisibleForTesting
    val featureComponents: MutableMap<Class<out BaseFeatureComponent.Builder<*>>, BaseFeatureComponent> = HashMap()
    private val featureActivityInjectors: MutableMap<Class<out BaseFeatureComponent.Builder<*>>, DispatchingAndroidInjector<Activity>> = HashMap()
    private val featureFragmentInjectors: MutableMap<Class<out BaseFeatureComponent.Builder<*>>, DispatchingAndroidInjector<Fragment>> = HashMap()

    ...

    fun <T : BaseFeatureComponent> featureActivityInjector(builder: BaseFeatureComponent.Builder<T>) =
            featureActivityInjectors.getOrPut(builder.javaClass) { (featureComponent(builder) as HasActivities).activityInjector() }

    fun <T : BaseFeatureComponent> featureFragmentInjector(builder: BaseFeatureComponent.Builder<T>) =
            featureFragmentInjectors.getOrPut(builder.javaClass) { (featureComponent(builder) as HasFragments).fragmentInjector() }

    private fun <T : BaseFeatureComponent> featureComponent(builder: BaseFeatureComponent.Builder<T>) =
            featureComponents.getOrPut(builder.javaClass) { builder.appComponent(appComponent).build() } as T
}
```
Fragments then inject like:
```kotlin
class ScreenOneFragment : Fragment() {
    override fun onAttach(context: Context) {
        featureFragmentInjector(DaggerFeatureOneComponent.builder()).inject(this)
        super.onAttach(context)
    }
}
```
The two rules mentioned in my previous answer populate the component cache upfront such that screens inside the features inject with the test components. Still gotta work on replacing objects provided in the dagger.android sub-components.

I hope this description is sufficient to understand the approach. I might put up a complete sample soon. But feedback is of course already very welcome :)
