### ISSUE TITLE
Provided Named Dependencies

### ISSUE THREAD

**Issue by krazykira** [fabioCollini/DaggerMock#84]
How to use the `provides` method to replace named dependencies inside the dependency graph ?

e.g
```
provides(
                @Named("Auth") OkHttpClient::class.java, // throws compile time error
                MockHttpClient.getClient())
```

Is there any other way to do this ?

**Comment by fabioCollini** [comment]
Not now, but it can be a useful feature. I'll try to implement it for the next release, thanks for the suggestion

**Comment by fabioCollini** [comment]
Hi @krazykira, I have implemented this feature in the last commit [383fa8003e](https://jitpack.io/#fabioCollini/DaggerMock/383fa8003e), can you try it using this commit as DaggerMock version?

In your example the syntax to use should be this:

     provides<OkHttpClient>("Auth", MockHttpClient.getClient())

Let me know if it works!

**Comment by olegivo** [comment]
@fabioCollini, it is work for me. Thank you!
Will you include this feature into next release and how soon?

**Comment by fabioCollini** [comment]
Released right now: https://jitpack.io/#fabioCollini/DaggerMock/0.8.5

**Comment by krazykira** [comment]
thanks. i will try it and let you know if i run into a problem
